### ISSUE TITLE
How to simply extract modelled optical depth?

### ISSUE THREAD

**Issue by bcappa** [tvwenger/amoeba2#9]
Hello,

I have run amoeba2 with some of my own OH data and it gave me traces of column density, velocity, excitation temperature etc. for each cloud.

I saw that within the source code that `TauModel()` has the function `predict_tau()` which looks like it calculates optical depth based on the fitting column density, FWHM, velocity and inverse excitation temperature.
I cannot easily figure out how to actually extract out the modelled optical depth spectra or modelled optical depth amplitude from the output of `predict_tau()`.

Essentially I want to pull out the best optical depth amplitude for each cloud and each OH transition so I can make my own 'best fit' optical depth model (together with the fitted FWHM and velocity) that I can compare that with my data and see what each model velocity component looks like.

I could estimate optical depth myself using the fitted column density, inverse excitation temperature, FWHM, velocity from the model, but since I see those equations already in the amobea2 code, it would be nice if I could just call a function and it tell me an optical depth value. Or maybe the code already does that and I'm just not understanding how to pull out those numbers?

**Comment by tvwenger** [comment]
Thanks for the suggestion @bcappa!

Unfortunately, I didn't write this model in such a way to make this visualization "easy". I've updated the `tau_model` tutorial with a demonstration of how one could use the mean posterior point estimate to visualize the contribution of individual clouds. This essentially breaks down what happens in `predict_tau`.
https://amoeba2.readthedocs.io/en/latest/notebooks/tau_model.html#Visualization-using-Mean-Point-Estimate

The reason `predict_tau()["1612"].eval()` doesn't work is because, without any arguments to `eval`, it simply evaluates the model with a random draw for the model parameters. You can pass parameters to eval, like `predict_tau()["1612"].eval({"velocity": [0.0], etc.})`, but because the model is specified to have `n_clouds`, you'd have to hack this pretty heavily to get it to work I think.

I'll think about easier ways to perform this visualization! A simple solution might be to move `predict_tau` to `physics.py` and pass the model parameters as arguments. That way one could independently call `predict_tau` with whatever parameters they want just to get the visualization. I would also need to implement a way to get the baseline model from `bayes_spec`. If you feel so-inclined, please consider submitting a pull request to refactor `predict_tau` into `physics.py`!
